coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: on
    patch: off
    changes: off

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "local"
  - "nmz_opt_lib"
  - "test"
  - "source/maxsimplex"
  - "source/dynamic"
