#ifndef CoCoA_PREPROCESSOR_DEFNS_H
#define CoCoA_PREPROCESSOR_DEFNS_H

// Created automatically by CoCoALib configure script.
// Created on date  2021-09-28  at time  12:39:31

// To enable debugging, reconfigure with option "--debug"
#undef CoCoA_DEBUG

// define CoCoA_MEMPOOL_DEBUG if you have memory problems
#undef CoCoA_MEMPOOL_DEBUG


#define CoCoA_ULONG2LONG 1

#define CoCoA_THREADSAFE_HACK
#undef CoCoA_WITH_BOOST
#undef CoCoA_WITH_NORMALIZ
#undef CoCoA_WITH_FROBBY
#undef CoCoA_WITH_GFAN
#undef CoCoA_WITH_MATHSAT
#undef CoCoA_WITH_GSL

#endif
